---
title: "saved_graphs"
author: "Joshua Berry"
date: "12/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(shiny)
library(tidyverse)
library(shinythemes)
library(gt)
library(gtsummary)
library(broom.mixed)
library(rstanarm)
```

## R Markdown

```{r}

# this page shows how I made the RDS files and then, eventually, took 
# screenshots of everything to add as PNGs. No new code was used except for
# the saveRDS() and the rest of the code was taken from previous work I had 
# done, mainly in ther server.

anes <- readRDS("chinese_military_threat.rds")

pew <- readRDS("pew.RDS")

basic_model <- readRDS("basic_model.rds")

basic_import_model <- readRDS("basic_import_model.RDS")

basic_export_model <- readRDS("basic_export_model.RDS")

model_variables <- readRDS("model_variables.RDS")

medium_export_model <- readRDS("medium_export_model.RDS")

complex_export_model <- readRDS("complex_export_model.RDS")

simple_export_demographic_model <- 
  readRDS("simple_export_demographic_model.RDS")

america_model <- readRDS("america_model.RDS")

load("36806-0001-Data.rda")
```

```{r}


readRDS("gdp_billions.RDS")

gdp_millions <-  
      pew %>%
      ggplot(aes(x = year, y = total_trade)) +
      geom_line(color = "blue") +
      facet_wrap(~COUNTRY) +
      labs(title = "GDP of Country by Year",
           subtitle = "The Effect of Total Trade Flow on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)",
           x = "Year",
           y = "GDP in Millions of US Dollars") +
      theme_classic()

saveRDS(gdp_millions, "gdp_millions.RDS")



export_millions <- 
    pew %>%
      ggplot(aes(x = year, y = china_exports)) +
      geom_line(color = "red") +
      facet_wrap(~COUNTRY) +
      labs(title = "Chinese Exports by year",
           subtitle = "The amount of Exports that China has sent to other G20 
            countries has varied over time",
           x = "Year",
           y = "Export Value in Millions of US Dollars") +
      theme_classic()

saveRDS(export_millions, "export_millions.RDS")

import_millions <-
    pew %>%
      ggplot(aes(x = year, y = china_imports)) +
      geom_line(color = "green") +
      facet_wrap(~COUNTRY) +
      labs(title = "Chinese Imports by Year",
           subtitle = "The amount of Imports that China has recieved from other 
    G20 members has varied over time",
           x = "Year",
           y = "Import Value in Millions of US Dollars") +
      theme_classic()

saveRDS(import_millions, "import_millions.RDS")
  

```

```{r}
basic_export_model_table <-  tbl_regression(basic_export_model, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Simple Imports Regression of Global Attitudes Torwards
             China", subtitle = "The Predicted Effect of Imports from China 
             Dependence on Favorability Towards China (1 = Very unfavorable,
             4 = Very favorable)") %>%
    tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

saveRDS(basic_export_model_table, "basic_export_model_table.RDS")


simple_trade <-  tbl_regression(basic_model, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
    as_gt() %>%
    tab_header(title = "Simple Total Trade Regression of Global Attitudes 
               Torwards China", 
               subtitle = "The Predicted Effect of Chinese Total Trade Flow 
               Dependence on Favorability Towards China (1 = Very unfavorable,
               4 = Very favorable)") %>%
    tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

saveRDS(simple_trade, "simple_trade.RDS")

simple_import <-   
  tbl_regression(basic_import_model, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
    as_gt() %>%
    tab_header(title = "Simple Exports Regression of Global Attitudes Torwards 
               China",
               subtitle = "The Predicted Effect of Exports to China Dependence 
               on Favorability Towards China (1 = Very unfavorable,
               4 = Very favorable)") %>%
    tab_source_note(md("Pew Global Attitudes & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

saveRDS(simple_import, "simple_import.RDS")

medium_export <-   
  tbl_regression(medium_export_model, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
    as_gt() %>%
    tab_header(title = "Medium Regression of Global Attitudes Torwards China",
               subtitle = "The Predicted Effect of Imports from China Dependence
               on Favorability Towards China (1 = Very unfavorable,
               4 = Very favorable)") %>%
    tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

saveRDS(medium_export, "medium_export.RDS")

complex_export <-
    tbl_regression(complex_export_model, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
    as_gt() %>%
    tab_header(title = "Complex Regression of Global Attitudes Torwards China",
               subtitle = "The Predicted Effect of Imports from China Dependence
               on Favorability Towards China (1 = Very unfavorable,
               4 = Very favorable)") %>%
    tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

saveRDS(complex_export, "complex_export.RDS")

demographic_export <-
  tbl_regression(simple_export_demographic_model, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
    as_gt() %>%
    tab_header(title = "Simple Regression of Global Attitudes
               (with Demographics) Torwards China",
               subtitle = "The Predicted Effect of Imports from China Dependence
               on Favorability Towards China (1 = Very unfavorable, 
               4 = Very favorable)") %>%
    tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

saveRDS(demographic_export, "demographic_export.RDS")

```


```{r}
country_facet <-
  pew %>%
      group_by(COUNTRY, year) %>%
      summarize(country_fav_prop = sum(fav_china_logistic, na.rm = TRUE)/n(),
                country_unfav_prop = sum(fav_china_logistic == 0, na.rm = TRUE)/n()) %>%
      ggplot(aes(x = year)) +
      geom_line(aes(y = country_fav_prop, color = "steelblue")) +
      geom_line(aes(y = country_unfav_prop, color = "darkred")) +
      facet_wrap(~ COUNTRY) +
      theme(axis.text = element_text(size = 5),
            axis.text.x = element_text(angle = 45),
            strip.text = element_text(size = 7),
            panel.grid = element_blank(), 
            panel.spacing.x = unit(3, "mm"),
            axis.ticks = element_blank()) +
      scale_x_continuous(breaks = c(2009:2019),
                         labels = c("2009", "", "", "", "", "", "", "", "", "", "2019")) +
      labs(title = "Increasingly negative evaluations of China across G20 economies",
           subtitle = "% who have a(n) view of China",
           x = "Year",
           y = "Public Opinion") +
      scale_color_discrete(name = "Favorable/Unfavorable",
                           labels = c("Unfavorable", "Favorable")) +
      theme_linedraw()

saveRDS(country_facet, "country_facet.RDS")


america_model_graph <-
      america_model %>% 
      as_tibble() %>% 
      select(-sigma) %>% 
      mutate(Democrat = `Q1025(2) Democratic`, Republican = `Q1025(1) Republican`,
             Neither = `Q1025(3) Neither`) %>%
      pivot_longer(cols = c(`Q1025(2) Democratic`,`Q1025(1) Republican`,
                            `Q1025(3) Neither`),
                   names_to = "parameter",
                   values_to = "Attitude") %>% 
      ggplot(aes(x = Attitude, color = parameter)) +
      geom_histogram(aes(y = after_stat(count/sum(count))),
                     alpha = 0.5, 
                     bins = 100, 
                     position = "identity") +
      scale_color_manual(name = "Party Affiliation",
                         labels = c("Republican", "Democrat", "Independent"),
                         values = c("firebrick1", "dodgerblue", "ivory4")) +
      labs(title = "Posterior Probability Distribution",
           subtitle = "Average attitude toward China; Chicago Council Survey 2016",
           x = "Attitude",
           y = "Probability") +
      scale_y_continuous(labels = scales::percent_format()) +
      theme_classic() +
      geom_vline(xintercept = 50, linetype = 'dashed')

saveRDS(america_model_graph, "america_model_graph.RDS")


feeling_therm <-
          da36806.0001 %>%
          ggplot(aes(x = Q45_6)) +
          geom_histogram(fill = "indianred", binwidth = 1) +
          scale_x_discrete(limits = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) +
          labs(title = "Americans' Feeling Thermometer Towards China ",
               subtitle = "0 = Very Cold; 50 = Not particuarly Warm or Cold;
                100 = Very Warm; Chicago Council Survey 2016",
               x = "American Feelings",
               y = "Count") +
          theme_bw()

saveRDS(feeling_therm, "feeling_therm.RDS")

party_post <-
          da36806.0001 %>%
          ggplot(aes(x = Q45_6, fill = Q1025)) +
          geom_boxplot() +
          facet_wrap(~ Q1025) +
          scale_fill_manual(values = c("salmon", "dodgerblue", "gold", "black")) +
          scale_fill_discrete(name = "Political Identification",
                              labels = c("Republican", "Democrat",
                                         "Independent", "Not asked Party Identification")) +
          labs(title = "Americans' Feeling Thermometer Towards China ",
               subtitle = "0 = Very Cold; 50 = Not particuarly Warm or Cold;
       100 = Very Warm; Chicago Council Survey 2016",
               x = "American Feelings",
               y = "Count") +
          theme_bw()

saveRDS(party_post, "party_post.RDS")

 anes_graph <-       
   anes %>%
          filter(china_mil %in% c(1, 2, 3)) %>%
          ggplot(aes(x = china_mil)) +
          geom_histogram(fill = "firebrick3", binwidth = 1, color = "white") +
          scale_x_discrete(limits = c("1", "2", "3"),
                           labels = c("Major threat", "Minor threat", "not a threat")) +
          labs(title = "Americans' Perspectives on the Chinese Military",
               subtitle = "Policy and attitudes toward China, ANES Survey 2012",
               x = "Chinese Military Threat",
               y = "Count") +
          theme_bw()
 
 saveRDS(anes_graph, "anes_graph.RDS")
 
  
 basic_plot <-
    basic_export_model %>%
      as_tibble() %>%
      ggplot(aes(x = `(Intercept)`)) +
      geom_histogram(aes(y = after_stat(count/sum(count))),
                     fill = "lightblue4",
                     color = "gray97",
                     bins = 100) +
      labs(title = "Posterior Probability Distribution of Global Attitudes
         Towards China",
           subtitle = "Predicted Effect of a 1% increase in Chinese Imports to
         GDP ration
          on Favorability Towards China (1 = Very unfavorable,
         4 = Very favorable)",
           x = "Predicted G20 Attitude Towards China",
           y = "Probability") +
      theme_classic()
 
  saveRDS(basic_plot, "basic_plot.RDS")
  
 trend_g20 <-
   pew %>%
      ggplot(aes(y = fav_china_scale, x = china_export_prop)) +
      geom_point(alpha = 100, color = "lavender") +
      geom_smooth(method = "glm", formula = y~x) +
      labs(title = "Yet among the aggregated G20 itself, views shift negative",
           x = "Ratio of Chinese Import Value to GDP (in USD)",
           y = "Attitudes towards China") +
      theme_bw() 
 
  saveRDS(trend_g20, "trend_g20.RDS")
  
  trend_country <-
        pew %>%
      ggplot(aes(y = fav_china_scale, x = china_export_prop)) +
      geom_point(alpha = 100, color = "gray") +
      geom_smooth(method = "glm", formula = y~x) +
      facet_wrap(~ COUNTRY) +
      labs(title = "Trends Differ According to Country",
           x = "Ratio of Chinese Import Value to GDP (in USD)",
           y = "Attitudes towards China") +
      theme_bw()
  
  saveRDS(trend_country, "trend_country.RDS")
```

