---
title: ""
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gganimate)
library(ggplot2)
library(tidyverse)
```

## R Markdown

```{r, echo=FALSE, message=FALSE, warning=FALSE}

# this rmd is home to my animation, saved as an html. Help and credit for
# helping with this animation goes to Wyatt Hurt. Essentially, I created
# and saved an HTML and then removed the title and other information so I could
# just show the HTML itself in my app.

pew <- readRDS("pew.RDS")

pew %>%
  group_by(COUNTRY, year) %>%
  summarize(country_fav_prop = sum(fav_china_logistic, na.rm = TRUE)/n(),
            country_unfav_prop = sum(fav_china_logistic == 0, na.rm = TRUE)/n()) %>%
  filter(COUNTRY == "United States") %>%
  ggplot(aes(x = year)) +
  geom_line(aes(y = country_fav_prop, color = "steelblue")) +
  geom_line(aes(y = country_unfav_prop, color = "darkred")) +
    theme(axis.text = element_text(size = 5),
          axis.text.x = element_text(angle = 45),
        strip.text = element_text(size = 7),
        panel.grid = element_blank(), 
        panel.spacing.x = unit(3, "mm"),
        axis.ticks = element_blank()) +
    scale_x_continuous(breaks = c(2009:2019),
                     labels = c("2009", "", "", "", "", "", "", "", "", "", "2019")) +
        labs(title = "American Evaluations of China across Time",
         subtitle = "% of Americans who have a(n) ___ view of China",
         x = "Year",
         y = "Public Opinion") +
    scale_color_discrete(name = "Favorable/Unfavorable", labels = c("Unfavorable", "Favorable")) +
    theme_classic() +
  transition_reveal(year)
```

