---
title: "gather"
author: "Joshua Berry"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(prettyR)
library(rstanarm)
library(ggridges)
library(gtsummary)
library(broom.mixed)
library(gt)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(DALEX)
library(tidymodels)
library(performance)
library(Metrics)
```

## R Markdown

```{r}
anes <- readstata13::read.dta13("anes_timeseries_2012.dta")

china_mil <-
  anes %>%
  select(china_mil)

saveRDS(china_mil, "chinese_military_threat.RDS")

anes %>%
  filter(china_mil %in% c(1, 2, 3)) %>%
  ggplot(aes(x = china_mil)) +
  geom_histogram(fill = "firebrick3") +
  scale_x_discrete(limits = c("1", "2", "3"),
                labels = c("Major threat", "Minor threat", "not a threat")) +
  labs(title = "Americans' Perspectives on the Chinese Military",
       subtitle = "Policy and attitudes toward China, ANES Survey 2012",
       x = "Chinese Military Threat",
       y = "Count") +
  theme_bw()
  
```

```{r}
ccouncil <- 
  load("Chicago_Council/ICPSR_36806/DS0001/36806-0001-Data.rda")

therm2016 <-
  da36806.0001 %>%
  select(Q45_6)

# saveRDS(therm, "china_therm_2016.RDS")

da36806.0001 %>%
  ggplot(aes(x = Q45_6)) +
  geom_histogram(fill = "red", binwidth = 1) +
  scale_x_discrete(limits = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) +
  labs(title = "Americans' Feeling Thermometer Towards China ",
       subtitle = "0 = Very Cold; 50 = Not particuarly Warm or Cold;
       100 = Very Warm; Chicago Council Survey 2016",
       x = "American Feelings",
       y = "Count") +
  theme_bw()

da36806.0001 %>%
  ggplot(aes(x = Q45_6, fill = Q1025)) +
  geom_boxplot() +
  facet_wrap(~ Q1025) +
  scale_fill_manual(values = c("salmon", "dodgerblue", "gold", "black")) +
  scale_fill_discrete(name = "Political Identification",
                    labels = c("Republican", "Democrat",
                            "Independent", "Not asked Party Identification")) +
  labs(title = "Americans' Feeling Thermometer Towards China ",
       subtitle = "0 = Very Cold; 50 = Not particuarly Warm or Cold;
       100 = Very Warm; Chicago Council Survey 2016",
       x = "American Feelings",
       y = "Count") +
  theme_bw()
```
```{r}
fit_obj <- stan_glm(Q45_6 ~ Q1025 -1,
                    data = da36806.0001,
                    refresh = 0)

fit_obj %>% 
  as_tibble() %>% 
  select(-sigma) %>% 
  mutate(Democrat = `Q1025(2) Democratic`, Republican = `Q1025(1) Republican`,
         Neither = `Q1025(3) Neither`) %>%
  pivot_longer(cols = c(`Q1025(2) Democratic`,`Q1025(1) Republican`,
                        `Q1025(3) Neither`),
               names_to = "parameter",
               values_to = "Attitude") %>% 
  ggplot(aes(x = Attitude, color = parameter)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   alpha = 0.5, 
                   bins = 100, 
                   position = "identity") +
  scale_color_manual(name = "Party Affiliation",
                       labels = c("Republican", "Democrat", "Independent"),
                     values = c("firebrick1", "dodgerblue", "ivory4")) +
  labs(title = "Posterior Probability Distribution",
      subtitle = "Average attitude toward China; Chicago Council Survey 2016",
      x = "Attitude",
      y = "Probability") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_classic() +
  geom_vline(xintercept = 50, linetype = 'dashed')
```

```{r}
pew <- readRDS("pew.RDS")   %>%
  mutate(china_export_prop = china_export_prop/1000000) %>%
  mutate(china_import_prop = china_import_prop/1000000) %>%
  mutate(trade_flow_prop = trade_flow_prop/1000000) %>%
  mutate(total_trade_billions = total_trade/1000)  %>%
  mutate(gdp_billions = gdp_tot/1000) %>%
  mutate(china_imports_billions = china_imports/1000) %>%
  mutate(china_exports_billions = china_exports/1000) %>%
  mutate(fav_china_logistic = case_when(fav_China == "Very unfavorable" ~ 0,
                                     fav_China == "Somewhat unfavorable" ~ 0,
                                     fav_China == "Somewhat favorable" ~ 1,
                                     fav_China == "Very favorable" ~ 1,
                                     TRUE ~ NA_real_)) 

pew <- pew %>%
  mutate(econ_sit = as.character(econ_sit)) %>%
  mutate(econ_sit = case_when(econ_sit == "Very good" ~ "Very good",
                                     econ_sit == "Somewhat good" ~ "Somewhat good",
                                     econ_sit == "Somewhat bad" ~ "Somewhat bad",
                                     econ_sit == "Very bad" ~ "Very bad",
                                     TRUE ~ NA_real_)) 


saveRDS(pew, "pew.RDS")

pew <- readRDS("pew.RDS")

set.seed(10)
basic_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ trade_flow_prop,
         refresh = 0)

tbl_regression(basic_model, intercept = TRUE) %>%
  as_gt() %>%
  tab_header(title = "Regression of Global Attitudes Torwards China",
             subtitle = "The Effect of Total Trade Flow Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

basic_export_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_export_prop,
         refresh = 0)

saveRDS(basic_export_model, "basic_export_model.RDS")

new_obs <- tibble(china_export_prop = input$user_percentage)

posterior_predict(basic_export_model, newdata = new_obs) %>%
  as_tibble() %>%
  mutate(across(everything(), as.numeric)) %>%
  ggplot(aes(x = `1`)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 150, color = "white", fill = "blue")  +
    labs(title = "Posterior Probability Distribution",
         subtitle = "For a __% change in Chinese Exports to X Country as percentage of GDP",
         x = "Predicted Median Attitude for All Countries on Pew Scale (1-4)",
         y = "Probability")  +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic()

tbl_regression(basic_export_model, intercept = TRUE) %>%
  as_gt() %>%
  tab_header(title = "Regression of Global Attitudes Torwards China",
             subtitle = "The Effect of Chinese Export Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

basic_import_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_import_prop,
         refresh = 0)

saveRDS(basic_import_model, "basic_import_model.RDS")


  

tbl_regression(basic_import_model, intercept = TRUE) %>%
  as_gt() %>%
  tab_header(title = "Regression of Global Attitudes Torwards China",
             subtitle = "The Effect of Chinese Export Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

set.seed(10)
billion_basic_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ total_trade_billions,
         refresh = 0)

print(billion_basic_model, digits = 5)

million_basic_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ total_trade,
         refresh = 0)



print(million_basic_model, digits = 5)

pew_basic_model <- saveRDS(basic_model, "basic_model.rds")

print(basic_model, digits = 5)

china_imports_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_import_prop,
         refresh = 0)


print(china_imports_model, digits = 4)

china_exports_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_export_prop,
         refresh = 0)

print(china_exports_model, digits = 4)

tbl_regression(basic_model, intercept = TRUE) %>%
  as_gt() %>%
  tab_header(title = "Regression of Global Attitudes Torwards China",
             subtitle = "The Effect of Total Trade Flow on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))


china_exports_model %>% 
  as_tibble() %>% 
  rename(mu = `(Intercept)`) %>%
  ggplot(aes(x = mu)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   fill = "lightblue4", 
                   color = "gray97",
                   bins = 100) +
    labs(title = "Probability Distribution of Global Attitudes Towards China",
         subtitle = "The Effect of Total Trade Flow on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)",
         x = "Attitudes Towards China",
         y = "Probability") +
    theme_classic()

pew %>%
  ggplot(aes(y = fav_china_logistic, x = trade_flow_prop)) +
  geom_point() +
  geom_smooth(method = "glm", method.args = list(family = "binomial"))

pew %>%
  ggplot(aes(y = fav_china_scale, x = total_trade_billions)) +
  geom_point(alpha = .7) + 
  scale_x_log10() +
  geom_smooth(method = "lm", formula = y~x, color = "darkmagenta")

pew %>%
  ggplot(aes(y = fav_china_scale, x = total_trade)) +
  geom_boxplot() +
  factor(~COUNTRY)
```
```{r}
# Tables creation


model_variables <- tibble(name = c("china_export_prop",
                              "china_import_prop", "trade_flow_prop", 
                              "econ_sit","country_satis", "satisfied_democracy",
                              "children_better0ff", "use_internet", "social_net",
                              "gender", "age"),
                     
                     # This row gives a description of the variables
                     
                     description = c("Total amount of Chinese originating imports of X Country (in USD)/Total GDP of
                                     X Country", 
                                     "Total amount of X Country originating exports towards China (in USD)/Total 
                                     GDP of X Country", 
                                    "Total amount of X Country and China Trade (in USD)/Total 
                                     GDP of X Country", 
                                    "Rated respondent opinion on their home country's economic situation",
                                    "Rated respondent opinion on whether they are satisfied or dissatsified
                                    with their country's current situation",
                                    "Rated respondent opinion on their satisfaction with democratic processes in
                                    their home country",
                                    "Rated respondent opinion on whether their children will have better lives
                                    in their home country than their parents",
                                    "Indicator of whether or not respondent regularly uses the internet",
                                    "Indicator of whether or not respondent regularly uses social media",
                                    "Indicator of respondent's 's gender",
                                    "Respondent's self-reported age"),
      
                     
                     # Was the variable in the simple model?
                     
                     simple = c("Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "No", "No"),
                    
                      simple_demographics = c("Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes", "Yes"),
                     
                     # Was the variable in the medium model?
                     
                     medium = c("Yes", "No", "No", "Yes", "No",
                                "No", "No", "No", "No", "No", "No"),
                     
                     # Was the variable in the complex model?
                     
                     complex = c("Yes", "No", "No", "Yes", "Yes",
                                "Yes", "Yes", "Yes", "Yes", "No", "No"),
                     
                     simple_Chinese_imports = c("No", "Yes", "No", "No", "No",
                                "No", "No", "No", "No", "No", "No"),
                     
                     simple_total_trade = c("No", "No", "Yes", "No", "No",
                                "No", "No", "No", "No", "No", "No")) %>%
  
  # Renaming columns to nicer things for display purposes
  
  rename("Variable name" = name, "Description" = description,
         "In Simple Model?" = simple, 
         "In Simple Demographics Model?" = simple_demographics,
         "In Medium Model?" = medium, 
         "In Complex Model?" = complex, 
         "In Simple Exports to China Model?" = simple_Chinese_imports,
         "In Simple Total Trade  Model?" = simple_total_trade)

# Saving this table to use later

saveRDS(model_variables, "model_variables.RDS")
```

```{r}

pew %>%
  group_by(COUNTRY, year) %>%
  summarize(country_fav_prop = sum(fav_china_logistic, na.rm = TRUE)/n(),
            country_unfav_prop = sum(fav_china_logistic == 0, na.rm = TRUE)/n()) %>%
  ggplot(aes(x = year)) +
  geom_line(aes(y = country_fav_prop, color = "steelblue")) +
  geom_line(aes(y = country_unfav_prop, color = "darkred")) +
  facet_wrap(~ COUNTRY) +
    theme(axis.text = element_text(size = 5),
          axis.text.x = element_text(angle = 45),
        strip.text = element_text(size = 7),
        panel.grid = element_blank(), 
        panel.spacing.x = unit(3, "mm"),
        axis.ticks = element_blank()) +
    scale_x_continuous(breaks = c(2009:2019),
                     labels = c("2009", "", "", "", "", "", "", "", "", "", "2019")) +
        labs(title = "Increasingly negative evaluations of China across G20 economies",
         subtitle = "% who have a(n) view of China",
         x = "Year",
         y = "Public Opinion") +
    scale_color_discrete(name = "Favorable/Unfavorable", labels = c("Unfavorable", "Favorable")) +
    theme_linedraw()
  

pew %>%
  group_by(COUNTRY, year) %>%
  summarize(country_fav_prop = sum(fav_china_logistic, na.rm = TRUE)/n(),
            country_unfav_prop = sum(fav_china_logistic == 0, na.rm = TRUE)/n()) %>%
  filter(COUNTRY == input$COUNTRY) %>%
  ggplot(aes(x = year)) +
  geom_line(aes(y = country_fav_prop, color = "steelblue")) +
  geom_line(aes(y = country_unfav_prop, color = "darkred")) +
    theme(axis.text = element_text(size = 5),
          axis.text.x = element_text(angle = 45),
        strip.text = element_text(size = 7),
        panel.grid = element_blank(), 
        panel.spacing.x = unit(3, "mm"),
        axis.ticks = element_blank()) +
    scale_x_continuous(breaks = c(2009:2019),
                     labels = c("2009", "", "", "", "", "", "", "", "", "", "2019")) +
        labs(title = "Evaluations of China across ____, a G20 economy",
         subtitle = "% who have a(n) view of China",
         x = "Year",
         y = "Public Opinion") +
    scale_color_discrete(name = "Favorable/Unfavorable", labels = c("Unfavorable", "Favorable")) +
    theme_linedraw()
  

```
```{r, trade flow}

pew %>%
  ggplot(aes(x = year, y = gdp_billions)) +
  geom_line(color = "blue") +
 facet_wrap(~COUNTRY) +
      labs(title = "GDP of Country by Year",
         subtitle = "The Effect of Total Trade Flow on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)",
         x = "Year",
         y = "GDP in Billions of US Dollars") +
    theme_classic()



pew %>%
 ggplot(aes(x = year, y = china_exports_billions)) +
  geom_line(color = "red") +
 facet_wrap(~COUNTRY) +
      labs(title = "Chinese Exports by Year",
         subtitle = "The amount of Exports that China sent to other G20 members
         has varied over time",
         x = "Year",
         y = "Export Value in Billions of US Dollars") +
    theme_classic()
  
pew %>%
 ggplot(aes(x = year, y = china_imports_billions)) +
  geom_line(color = "green") +
 facet_wrap(~COUNTRY) +
      labs(title = "Chinese Imports by Year",
         subtitle = "The amount of Imports that China has recieved from other G20 members
         has varied over time",
         x = "Year",
         y = "Import Value in Billions of US Dollars") +
    theme_classic()



```
```{r}

trade_flow_data <- data.frame(
  name = c("Argentina", "Australia", "Brazil", "Canada", "France",
                      "Germany", "India", "Indonesia", "Italy", "Japan",
                      "Mexico", "Russia", "South Africa", "Korea",
                       "Turkey", "United Kingdom", "United States"),
  trade_flow_data = c(1.383301, 11.81229, 2.901576, 3.360795, 1.981375, 3.948714,
             1.040185, 2.391821, 2.055134, 5.765495, 2.332136, 2.562977,
             5.58519, 12.75449, 0.8871423, 2.645502, 2.527944)
)

world <- ne_countries(scale = "medium", returnclass = "sf") %>%
  left_join(trade_flow_data, by = "name")
  
class(world)


map_trade <- ggplot(data = world) +
    geom_sf(aes(fill = trade_flow_data)) +
    scale_fill_viridis_c(trans = "sqrt",
                         name = "Trade w/ China as % of GDP") +
   ggtitle("Trade between China and _____ G20 Country as a % of ______ Country's GDP 
           (imports + exports with China / total GDP, proportion)", 
           subtitle = "Among 17 of 20 G20 members") +
  theme_classic()

ggsave("map_trade.png", map_trade)
```

```{r}
basic_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ trade_flow_prop,
         refresh = 0)

saveRDS(basic_model, "basic_model.RDS")

tbl_regression(basic_model, intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Regression of Global Attitudes Torwards China",
             subtitle = "The Predicted Effect of Chinese Total Trade Flow Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

basic_export_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_export_prop,
         refresh = 0)

saveRDS(basic_export_model, "basic_export_model.RDS")

tbl_regression(basic_export_model, intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Regression of Global Attitudes Torwards China",
             subtitle = "The Predicted Effect of Imports from China Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

medium_export_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_export_prop + econ_sit,
         refresh = 0)

saveRDS(medium_export_model, "medium_export_model.RDS")

tbl_regression(medium_export_model, intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Medium Regression of Global Attitudes Torwards China",
             subtitle = "The Predicted Effect of Imports from China Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

complex_export_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_export_prop + econ_sit + country_satis +
           satisfied_democracy + children_betteroff + use_internet + social_net,
         refresh = 0)

saveRDS(complex_export_model, "complex_export_model.RDS")

tbl_regression(complex_export_model, intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Complex Regression of Global Attitudes Torwards China",
             subtitle = "The Predicted Effect of Imports from China Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))

simple_export_demographic_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_export_prop + sex + age,
         refresh = 0)

saveRDS(simple_export_demographic_model, "simple_export_demographic_model.RDS")

tbl_regression(simple_export_demographic_model, intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Medium Regression of Global Attitudes Torwards China",
             subtitle = "The Predicted Effect of Imports from China Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attidues & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))


basic_import_model <- stan_glm(data = pew,
         formula = fav_china_scale ~ china_import_prop,
         refresh = 0)

saveRDS(basic_import_model, "basic_import_model.RDS")



tbl_regression(basic_import_model, intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Regression of Global Attitudes Torwards China",
             subtitle = "The Predicted Effect of Exports to China Dependence on Favorability 
             Towards China (1 = Very unfavorable, 4 = Very favorable)") %>%
  tab_source_note(md("Pew Global Attitudes & Trends Survey (2009-2019), 
                     IMF World Trade Flows (2009-2019),
                     World Bank G20 GDPs (2019-2019)"))
```


```{r}
# metrics

performance_rmse(basic_export_model, normalized = FALSE)

rmse(basic_import_model, normalized = FALSE)

performance_rmse(basic_model, normalized = FALSE)

performance_rmse(medium_export_model, normalized = FALSE)

performance_rmse(simple_export_demographic_model, normalized = FALSE)

performance_rmse(complex_export_model, normalized = FALSE)

  model_error_tbl <- tibble("Model Name" = c("Simple Model", "Simple Demographics Model",
                                             "Medium Model", "Complex Model", 
                                             "Simple Exports to China Model", 
                                             "Simple Total Trade Model"),
                            "Standard Error" = c(.8967, .8930, .8935, .8873, .8975, .8975))
  
  print(basic_model, digits = 4)
  rmse(pew$fav_china_scale, basic_export_model)
```
```{r}
pew %>%
  ggplot(aes(y = fav_china_scale, x = china_export_prop)) +
  geom_point(alpha = 100, color = "gray") +
  geom_smooth(method = "glm", formula = y~x) +
facet_wrap(~ COUNTRY) +
  labs(title = "Trends Differ According to Country",
       x = "Ratio of Chinese Import Value to GDP (in USD)",
       y = "Attitudes towards China") +
  theme_bw()

pew %>%
  ggplot(aes(y = fav_china_scale, x = china_export_prop)) +
  geom_point(alpha = 100, color = "lavender") +
  geom_smooth(method = "glm", formula = y~x) +
  labs(title = "Yet among the aggregated G20 itself, viwes shift negative",
       x = "Ratio of Chinese Import Value to GDP (in USD)",
       y = "Attitudes towards China") +
  theme_bw()
```

